// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.4

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type ActivityHTTPServer interface {
	CreateActivity(context.Context, *CreateActivityRequest) (*CreateActivityReply, error)
	DeleteActivity(context.Context, *DeleteActivityRequest) (*DeleteActivityReply, error)
	GetActivity(context.Context, *GetActivityRequest) (*GetActivityReply, error)
	ListActivity(context.Context, *ListActivityRequest) (*ListActivityReply, error)
	UpdateActivity(context.Context, *UpdateActivityRequest) (*UpdateActivityReply, error)
}

func RegisterActivityHTTPServer(s *http.Server, srv ActivityHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/activity", _Activity_CreateActivity0_HTTP_Handler(srv))
	r.PUT("/v1/activity/{id}", _Activity_UpdateActivity0_HTTP_Handler(srv))
	r.DELETE("/v1/activity/{id}", _Activity_DeleteActivity0_HTTP_Handler(srv))
	r.GET("/v1/activity/{id}", _Activity_GetActivity0_HTTP_Handler(srv))
	r.GET("/v1/activity/List", _Activity_ListActivity0_HTTP_Handler(srv))
}

func _Activity_CreateActivity0_HTTP_Handler(srv ActivityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateActivityRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.activity.v1.activity/CreateActivity")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateActivity(ctx, req.(*CreateActivityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateActivityReply)
		return ctx.Result(200, reply)
	}
}

func _Activity_UpdateActivity0_HTTP_Handler(srv ActivityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateActivityRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.activity.v1.activity/UpdateActivity")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateActivity(ctx, req.(*UpdateActivityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateActivityReply)
		return ctx.Result(200, reply)
	}
}

func _Activity_DeleteActivity0_HTTP_Handler(srv ActivityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteActivityRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.activity.v1.activity/DeleteActivity")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteActivity(ctx, req.(*DeleteActivityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteActivityReply)
		return ctx.Result(200, reply)
	}
}

func _Activity_GetActivity0_HTTP_Handler(srv ActivityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetActivityRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.activity.v1.activity/GetActivity")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetActivity(ctx, req.(*GetActivityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetActivityReply)
		return ctx.Result(200, reply)
	}
}

func _Activity_ListActivity0_HTTP_Handler(srv ActivityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListActivityRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.activity.v1.activity/ListActivity")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListActivity(ctx, req.(*ListActivityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListActivityReply)
		return ctx.Result(200, reply)
	}
}

type ActivityHTTPClient interface {
	CreateActivity(ctx context.Context, req *CreateActivityRequest, opts ...http.CallOption) (rsp *CreateActivityReply, err error)
	DeleteActivity(ctx context.Context, req *DeleteActivityRequest, opts ...http.CallOption) (rsp *DeleteActivityReply, err error)
	GetActivity(ctx context.Context, req *GetActivityRequest, opts ...http.CallOption) (rsp *GetActivityReply, err error)
	ListActivity(ctx context.Context, req *ListActivityRequest, opts ...http.CallOption) (rsp *ListActivityReply, err error)
	UpdateActivity(ctx context.Context, req *UpdateActivityRequest, opts ...http.CallOption) (rsp *UpdateActivityReply, err error)
}

type ActivityHTTPClientImpl struct {
	cc *http.Client
}

func NewActivityHTTPClient(client *http.Client) ActivityHTTPClient {
	return &ActivityHTTPClientImpl{client}
}

func (c *ActivityHTTPClientImpl) CreateActivity(ctx context.Context, in *CreateActivityRequest, opts ...http.CallOption) (*CreateActivityReply, error) {
	var out CreateActivityReply
	pattern := "/v1/activity"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.activity.v1.activity/CreateActivity"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ActivityHTTPClientImpl) DeleteActivity(ctx context.Context, in *DeleteActivityRequest, opts ...http.CallOption) (*DeleteActivityReply, error) {
	var out DeleteActivityReply
	pattern := "/v1/activity/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.activity.v1.activity/DeleteActivity"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ActivityHTTPClientImpl) GetActivity(ctx context.Context, in *GetActivityRequest, opts ...http.CallOption) (*GetActivityReply, error) {
	var out GetActivityReply
	pattern := "/v1/activity/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.activity.v1.activity/GetActivity"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ActivityHTTPClientImpl) ListActivity(ctx context.Context, in *ListActivityRequest, opts ...http.CallOption) (*ListActivityReply, error) {
	var out ListActivityReply
	pattern := "/v1/activity/List"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.activity.v1.activity/ListActivity"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ActivityHTTPClientImpl) UpdateActivity(ctx context.Context, in *UpdateActivityRequest, opts ...http.CallOption) (*UpdateActivityReply, error) {
	var out UpdateActivityReply
	pattern := "/v1/activity/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.activity.v1.activity/UpdateActivity"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
