package common

const (
	ACTIVITY_STATE_EDIT        = 1
	ACTIVITY_STATE_ARRAIGNMENT = 2
	ACTIVITY_STATE_REVOKE      = 3
	ACTIVITY_STATE_PASS        = 4
	ACTIVITY_STATE_DOING       = 5
	ACTIVITY_STATE_REFUSE      = 6
	ACTIVITY_STATE_CLOSE       = 7
	ACTIVITY_STATE_OPEN        = 8
)
